CONFIG_NAME: 'RESNET34'
DATASET_NAME: TUNE_ELEM_AI
COMET_ML_UPLOAD: False
SEED: 8

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  VALID_SPLIT: 0.1 
  TEST_SPLIT: 0.0
  SAMPLE_SIZE: 1080 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 16 # 64 # small batch size # resnet18 can handle 350 batches, resnet50 64
  NUM_EPOCHS: 50 # minimal number of epoches just to see it's training
  MAX_PATIENCE: 38 # less than num_ep
  LR_SCHEDULER_PARAMS:
    MILESTONES: [20,40]
    GAMMA: 0.1
  NUM_WORKER: 0
MODEL:
  FEATURES_EXTRACTION:
    BLOCK: "basic"
    LAYERS: [
      3,
      4,
      6,
      3
    ]
  LENGTH_CLASSIFIER:
    NUM_CLASSES: 7
  NUMBER_CLASSIFIER:
    MAX_SEQUENCE_LENGTH: 5
    NUM_CLASSES: 10
HYPER_PARAMS:
  N_CALLS: 5
  SPACE:
    LR: [0.0001,0.01]
    MOM: [0.90,0.91]
    WEIGHT_DECAY: [0.0001, 0.001]
    DECAY_STEPS: [10000, 10001]
    DECAY_RATE: [0.89, 0.90]
    FEATURES_OUTPUT_SIZE: [3000,6000]
  INITIAL_VALUES:
    LR: 0.001
    MOM: 0.90460279888176
    WEIGHT_DECAY: 0.00011294798735631021
    DECAY_STEPS: 10001
    DECAY_RATE: 0.8963831163393121
    FEATURES_OUTPUT_SIZE: 4277
    