CONFIG_NAME: 'RESNET34_FROM_B2'
DATASET_NAME: ELEM_AI
COMET_ML_UPLOAD: False
SEED: 23

# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  VALID_SPLIT: 0.1 
  TEST_SPLIT: 0.1
  SAMPLE_SIZE: -1 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  BATCH_SIZE: 32 # small batch size # resnet18 can handle 350 batches, resnet50 64
  NUM_EPOCHS: 400 # minimal number of epoches just to see it's training
  MAX_PATIENCE: 320 # less than num epo in order to autosave
  LR_SCHEDULER_PARAMS:
    MILESTONES: [90,150]
    GAMMA: 0.1
  NUM_WORKER: 0
MODEL:
  FEATURES_EXTRACTION:
    BLOCK: "basic"
    LAYERS: [
      3,
      4,
      6,
      3
    ]
  LENGTH_CLASSIFIER:
    NUM_CLASSES: 7
  NUMBER_CLASSIFIER:
    MAX_SEQUENCE_LENGTH: 5
    NUM_CLASSES: 10
HYPER_PARAMS:
  N_CALLS: 5
  SPACE:
    LR: [0.0001,0.01]
    MOM: [0.90,0.91]
    WEIGHT_DECAY: [0.0001, 0.001]
    DECAY_STEPS: [10000, 10001]
    DECAY_RATE: [0.89, 0.90]
    FEATURES_OUTPUT_SIZE: [3000,6000]
  INITIAL_VALUES:
    LR: 0.000098
    MOM: 0.9
    WEIGHT_DECAY: 0.0005
    DECAY_STEPS: 10000
    DECAY_RATE: 0.9
    FEATURES_OUTPUT_SIZE: 4096
